name: flutter_europe_compass
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.3.2
  location: ^2.3.5
  after_layout: ^1.0.7+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/compass.jpg
    - assets/flutter_europe.png